// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";
import { SUPABASE_PUBLIC_PUBLISHABLE_KEY, SUPABASE_PUBLIC_URL } from "./public-config";

function createSupabaseClient() {
  // VITE_* values override the public fallback in public-config.ts.
  // Never read process.env from browser code: Lovable preview builds may not expose it.
  const SUPABASE_URL = SUPABASE_PUBLIC_URL;
  const SUPABASE_PUBLISHABLE_KEY = SUPABASE_PUBLIC_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const message = "Missing browser-safe Supabase configuration.";
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Pass publishable keys directly to supabase-js. Current Supabase clients and
  // gateways own the apikey/Authorization header contract; rewriting those headers
  // here can break password sign-in and authenticated requests.
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
